baseURL = "/"
languageCode = "en-us"
title = "Safety Down Under"
theme = "hugo-hero-theme"
themesDir = "themes"

[module]

[module.hugoVersion]
extended = true
min = "0.92.0"

[params]
google_analytics_id = ""
custom_css = ["css/contact_form.css", "css/logo.css"]

[params.logo]
mobile = "favicons/android-chrome-192x192.png"
mobile_height = "10px"
mobile_width  = "10px"
desktop = "images/sdu_logo-removebg.png"
desktop_height = "50px"
desktop_width  = "50px"
alt = "Safety Down Under"

[params.homepage_meta_tags]
meta_description = "Your home for playground safety."
meta_og_title = "Safety Down Under"
meta_og_type = "website"
meta_og_url = "https://hugo-hero.netlify.app"
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
meta_og_description = "Your home for playground safety."
meta_twitter_card = "summary"
meta_twitter_site = "@zerostaticio"
meta_twitter_creator = "@zerostaticio"

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

[[menu.main]]
name = "Work"
url = "/work/"
weight = 2

[[menu.main]]
name = "Vendors"
url = "/vendors/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[permalinks]
post = "/:year/:month/:day/:slug/"
pages = "/:filename/"
